[build]
  command = "npm run build"
  publish = ".next"

[context.production.environment]
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"
