// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Sidebar from "@/components/common/Sidebar/Sidebar";
// import ReduxProvider from "@/components/ReduxProvider";
// import { Toaster } from "react-hot-toast";
// import "@radix-ui/themes/styles.css";
// import { Theme } from "@radix-ui/themes";
// import { AuthProvider } from "@/context/AuthProvider";
// import { SessionProvider } from "next-auth/react";
// import { AppProps } from "next/app";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "YarnWise",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   Component,
//   pageProps: { session, ...pageProps },
// }: AppProps) {
//   return (
//     <html lang="en">
//       <head>{/* Meta tags, links, and other head elements */}</head>
//       <body className={inter.className}>
//         <SessionProvider session={session}>
//           <AuthProvider>
//             <ReduxProvider>
//               <Theme>
//                 <div className="flex">
//                   <Sidebar />
//                   <div className="flex-1">
//                     <Toaster />
//                     <Component {...pageProps} />
//                   </div>
//                 </div>
//               </Theme>
//             </ReduxProvider>
//           </AuthProvider>
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/common/Sidebar/Sidebar';
import ReduxProvider from '@/components/ReduxProvider';
import { Toaster } from 'react-hot-toast';
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import { AuthProvider } from '@/context/AuthProvider';
import { ReactNode } from 'react';
import SessionProviderWrapper from '@/components/SessionProviderWrapper';
import Navbar from '@/components/common/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'YarnWise',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
  session: any;
}

export default function RootLayout({ children, session }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>{/* Meta tags, links, and other head elements */}</head>
      <body className={inter.className}>
        <SessionProviderWrapper session={session}>
          <AuthProvider>
            <ReduxProvider>
              <Theme>
                <div className="flex">
                  <Sidebar />
                  
                  <div className="flex-1">
                    <Toaster />
                    <Navbar />
                    {children}
                  </div>
                </div>
              </Theme>
            </ReduxProvider>
          </AuthProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
